version: '3.7'

services:
    app:
        image: node:16.10.0-alpine3.14
        container_name: safeotc.demo
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./:/app
        working_dir: /app
        environment:
            - .docker-compose.env
        command: npm run dev
